
CREATE TABLE IF NOT EXISTS tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    first_name TEXT NOT NULL CHECK (first_name <> ''),
    last_name TEXT NOT NULL CHECK (last_name <> ''),
    email VARCHAR(50) NOT NULL,
    tel VARCHAR(30) NOT NULL, 
    date_of_birth DATE NOT NULL,
    UNIQUE(email)
);